#!/bin/bash


# Print banner
echo "StegCracker - ($PROJECT_URL)"
echo "Copyright (c) $(date +%Y) - Luke Paris (Paradoxis)"
echo

# Print usage / Load arguments
if [ $# -eq 0 ]; then
    echo "Usage: <candidates> | $0 <file>"
    exit 1
fi

# Ensure steghide is installed
if [[ ! $(which steghide) ]]; then
    echo -e "\x1B[31mError:\x1B[0m Steghide does not appear to be installed, or has not been added to your current PATH."

    if [[ $(cat /etc/issue | grep Kali && which apt-get) ]]; then
        echo "       You can install it by running the following command: apt-get install steghide -y"
    fi

    exit 1
fi

# Ensure the input file exists
if [ ! -f $1 ]; then
   echo -e "\x1B[31mError:\x1B[0m File '$1' does not exist!"
   exit 1
fi

# Ensure the file is steghide compatible
if [[ ! $(echo "jpg jpeg bmp wav au" | grep -i "${1##*.}") ]]; then
    echo -e "\x1B[31mError:\x1B[0m Unsupported file type '${1##*.}'! Supported extensions: jpg, jpeg, bmp, wav, au"
    exit 1
fi

# Ensure we don't accidentally overwrite a file
if [ -f $1.out ]; then
   echo -e "\x1B[31mError:\x1B[0m Output file '$1.out' already exists!"
   exit 1
fi

# Print message indicating we've started cracking the file
echo "Attacking file '$1' with candidates from stdin"

while IFS= read -r pass; do

    # Calculate progress
    line=$((line + 1))

    # Crack the file and quit upon finding the right one
    steghide extract -sf $1 -xf $1.out -p "$pass" -f > /dev/null 2>&1 &
    if [[ -z $1.out ]]; then
        echo "Successfully cracked file with password: $pass"
        echo "Tried $line passwords"
        echo "Your file has been written to: $1.out"
        exit 0
    else
        echo -en "$line Attempted: $pass\033[0K\r"
    fi
done < /dev/stdin

# If we didn't exit before this point, we probably failed
echo -e "\x1B[31mError:\x1B[0m Failed to crack file, ran out of passwords."
exit 1
